#!/bin/bash
# setup the directories

currentDir=`pwd`
fastaDir=${currentDir}/Project_2016_09_23_Ji/
# mkdir workdata
# mkdir casc cent chin colb fugg gold mtho nugg sora wila

dirList=`ls ${currentDir}/workdata/`

# create dirs for assembly and soft link to the ref genome
for dirName in $dirList
	do
		mkdir workdata/${dirName}/rib-aln
		# mkdir workdata/${dirName}/contigs/novoplasty
		# mkdir workdata/${dirName}/contigs/soap
		# cp seed.fasta workdata/${dirName}/contigs/novoplasty/seed.fasta
		# mkdir workdata/${dirName}/aln
		# ln -s ${currentDir}/ncbi-ref-genome.fa workdata/${dirName}/aln
	done


# ln -s ${fastaDir}Sample_CASC/CASC_TATCAGCA_L007_R1_001.fastq.gz ~/Documents/hops/workdata/casc/CASC_TATCAGCA_L007_R1_001.fastq.gz
# ln -s ${fastaDir}Sample_CASC/CASC_TATCAGCA_L007_R2_001.fastq.gz ~/Documents/hops/workdata/casc/CASC_TATCAGCA_L007_R2_001.fastq.gz
#
# ln -s ${fastaDir}Sample_CENT/CENT_GTGTTCTA_L007_R1_001.fastq.gz ~/Documents/hops/workdata/cent/CENT_GTGTTCTA_L007_R1_001.fastq.gz
# ln -s ${fastaDir}Sample_CENT/CENT_GTGTTCTA_L007_R2_001.fastq.gz ~/Documents/hops/workdata/cent/CENT_GTGTTCTA_L007_R2_001.fastq.gz
#
# ln -s ${fastaDir}Sample_CHIN/CHIN_TCCGTCTA_L007_R1_001.fastq.gz ~/Documents/hops/workdata/chin/CHIN_TCCGTCTA_L007_R1_001.fastq.gz
# ln -s ${fastaDir}Sample_CHIN/CHIN_TCCGTCTA_L007_R1_002.fastq.gz ~/Documents/hops/workdata/chin/CHIN_TCCGTCTA_L007_R1_002.fastq.gz
# ln -s ${fastaDir}Sample_CHIN/CHIN_TCCGTCTA_L007_R2_001.fastq.gz ~/Documents/hops/workdata/chin/CHIN_TCCGTCTA_L007_R2_001.fastq.gz
# ln -s ${fastaDir}Sample_CHIN/CHIN_TCCGTCTA_L007_R2_002.fastq.gz ~/Documents/hops/workdata/chin/CHIN_TCCGTCTA_L007_R2_002.fastq.gz
#
# ln -s ${fastaDir}Sample_COLB/COLB_TGGAACAA_L007_R1_001.fastq.gz ~/Documents/hops/workdata/colb/COLB_TGGAACAA_L007_R1_001.fastq.gz
# ln -s ${fastaDir}Sample_COLB/COLB_TGGAACAA_L007_R1_002.fastq.gz ~/Documents/hops/workdata/colb/COLB_TGGAACAA_L007_R1_002.fastq.gz
# ln -s ${fastaDir}Sample_COLB/COLB_TGGAACAA_L007_R2_001.fastq.gz ~/Documents/hops/workdata/colb/COLB_TGGAACAA_L007_R2_001.fastq.gz
# ln -s ${fastaDir}Sample_COLB/COLB_TGGAACAA_L007_R2_002.fastq.gz ~/Documents/hops/workdata/colb/COLB_TGGAACAA_L007_R2_002.fastq.gz
#
# ln -s ${fastaDir}Sample_FUGG/FUGG_TGAAGAGA_L007_R1_001.fastq.gz ~/Documents/hops/workdata/fugg/FUGG_TGAAGAGA_L007_R1_001.fastq.gz
# ln -s ${fastaDir}Sample_FUGG/FUGG_TGAAGAGA_L007_R2_001.fastq.gz ~/Documents/hops/workdata/fugg/FUGG_TGAAGAGA_L007_R2_001.fastq.gz
#
# ln -s ${fastaDir}Sample_GOLD/GOLD_TCTTCACA_L007_R1_001.fastq.gz ~/Documents/hops/workdata/gold/GOLD_TCTTCACA_L007_R1_001.fastq.gz
# ln -s ${fastaDir}Sample_GOLD/GOLD_TCTTCACA_L007_R1_002.fastq.gz ~/Documents/hops/workdata/gold/GOLD_TCTTCACA_L007_R1_002.fastq.gz
# ln -s ${fastaDir}Sample_GOLD/GOLD_TCTTCACA_L007_R2_001.fastq.gz ~/Documents/hops/workdata/gold/GOLD_TCTTCACA_L007_R2_001.fastq.gz
# ln -s ${fastaDir}Sample_GOLD/GOLD_TCTTCACA_L007_R2_002.fastq.gz ~/Documents/hops/workdata/gold/GOLD_TCTTCACA_L007_R2_002.fastq.gz
#
# ln -s ${fastaDir}Sample_MTHO/MTHO_TAGGATGA_L007_R1_001.fastq.gz ~/Documents/hops/workdata/mtho/MTHO_TAGGATGA_L007_R1_001.fastq.gz
# ln -s ${fastaDir}Sample_MTHO/MTHO_TAGGATGA_L007_R2_001.fastq.gz ~/Documents/hops/workdata/mtho/MTHO_TAGGATGA_L007_R2_001.fastq.gz
#
# ln -s ${fastaDir}Sample_NUGG/NUGG_TGGCTTCA_L007_R1_001.fastq.gz ~/Documents/hops/workdata/nugg/NUGG_TGGCTTCA_L007_R1_001.fastq.gz
# ln -s ${fastaDir}Sample_NUGG/NUGG_TGGCTTCA_L007_R2_001.fastq.gz ~/Documents/hops/workdata/nugg/NUGG_TGGCTTCA_L007_R2_001.fastq.gz
#
# ln -s ${fastaDir}Sample_SORA/SORA_TTCACGCA_L007_R1_001.fastq.gz ~/Documents/hops/workdata/sora/SORA_TTCACGCA_L007_R1_001.fastq.gz
# ln -s ${fastaDir}Sample_SORA/SORA_TTCACGCA_L007_R2_001.fastq.gz ~/Documents/hops/workdata/sora/SORA_TTCACGCA_L007_R2_001.fastq.gz
#
# ln -s ${fastaDir}Sample_WILA/WILA_TGGTGGTA_L007_R1_001.fastq.gz ~/Documents/hops/workdata/wila/WILA_TGGTGGTA_L007_R1_001.fastq.gz
# ln -s ${fastaDir}Sample_WILA/WILA_TGGTGGTA_L007_R2_001.fastq.gz ~/Documents/hops/workdata/wila/WILA_TGGTGGTA_L007_R2_001.fastq.gz
