#!/bin/bash
set -e
currentDir=`pwd`
refFasta=${currentDir}/genome-ref/chloroplast-reference-genome.fasta
adapterSeq=${currentDir}/Trimmomatic-0.36/adapters/TruSeq3-PE.fa
trimmomaticjar=${currentDir}/Trimmomatic-0.36/trimmomatic-0.36.jar
workdata=`ls ${currentDir}/workdata/`

# workdata=( "casc" )
workdata=( "casc" "cent" "colb" "fugg" "gold" "mtho" "nugg" "sora" "wila" )

# index ref genome
bwa index $refFasta

for dirName in ${workdata[@]}
do
    seqPref=`echo $dirName | tr [:lower:] [:upper:]`

    # echo "########################### trimming start: ${dirName} ###############################"
    # java -jar $trimmomaticjar PE -threads 8 -phred33 ${currentDir}/workdata/$dirName/${seqPref}_*_L007_R1_001.fastq.gz ${currentDir}/workdata/$dirName/${seqPref}_*_L007_R2_001.fastq.gz ${currentDir}/workdata/$dirName/${seqPref}_R1.fastq.gz ${currentDir}/workdata/$dirName/bak1 ${currentDir}/workdata/$dirName/${seqPref}_R2.fastq.gz ${currentDir}/workdata/$dirName/bak2 ILLUMINACLIP:$adapterSeq:2:30:12:1 LEADING:20 TRAILING:20 HEADCROP:10 SLIDINGWINDOW:4:20 MINLEN:80
    #
    # if [ $? != 0 ]; then
    #     echo "trimming went wrong: ${dirName}"
    #     exit 1
    # fi


    # echo "########################### assembly start: ${dirName} ###############################"
    # abyss-pe -C ${currentDir}/workdata/$dirName/contigs name=$dirName k=48 v=-v in="${currentDir}/workdata/$dirName/${seqPref}_R1.fastq.gz ${currentDir}/workdata/$dirName/${seqPref}_R2.fastq.gz" contigs 2>&1 | tee ${currentDir}/workdata/$dirName/contigs/abyss.log
    #
    # if [ $? != 0 ]; then
    #     echo "assembly went wrong: ${dirName}"
    #     exit 1
    # fi


    echo "########################### reads alignment start: ${dirName} ###############################"

    bwa mem -R '@RG\tID:HWI-ST765\tSM:sample1\tLB:None\tPL:Illumina' $refFasta ${currentDir}/workdata/${dirName}/${seqPref}_R1.fastq.gz ${currentDir}/workdata/${dirName}/${seqPref}_R2.fastq.gz > ${currentDir}/workdata/${dirName}/aln/${dirName}-reads.sam

    if [ $? != 0 ]; then
        echo "reads alignment went wrong: ${dirName}"
        exit 1
    fi


    echo "########################### sam processing start: ${dirName} ###############################"

    samtools view -F 4 -bh ${currentDir}/workdata/${dirName}/aln/${dirName}-reads.sam | samtools sort -n - | samtools fixmate -m - ${currentDir}/workdata/${dirName}/aln/${dirName}-reads.fix.bam &&
    samtools sort ${currentDir}/workdata/${dirName}/aln/${dirName}-reads.fix.bam | samtools markdup -r - ${currentDir}/workdata/${dirName}/aln/${dirName}-reads.sorted.bam &&
    samtools index ${currentDir}/workdata/${dirName}/aln/${dirName}-reads.sorted.bam


    echo "########################### variance call start: ${dirName} ###############################"

    freebayes -f ${refFasta} --ploidy 1 \
                             --haplotype-length 0 \
                             --min-alternate-count 1 \
                             --min-alternate-fraction 0 \
                             --pooled-continuous \
                             --min-base-quality 20 \
                             --min-mapping-quality 20 \
                             ${currentDir}/workdata/${dirName}/aln/${dirName}-reads.sorted.bam | vcffilter -f "QUAL > 20" >  ${currentDir}/workdata/${dirName}/aln/${dirName}-freebayes-filtered-variance.vcf &&

    rtg vcfstats ${currentDir}/workdata/${dirName}/aln/${dirName}-freebayes-filtered-variance.vcf > ${currentDir}/workdata/${dirName}/aln/${dirName}-freebayes-filtered-variance.stats

    # bcftools mpileup -Ou -f $refFasta ${currentDir}/workdata/${dirName}/aln/${dirName}-reads.sorted.bam | bcftools call -vmO z -o ${currentDir}/workdata/${dirName}/aln/${dirName}-variance.vcf.gz &&
    # tabix -p vcf ${currentDir}/workdata/${dirName}/aln/${dirName}-variance.vcf.gz &&
    # bcftools filter -e '%QUAL<20' -g5 -G10 -o ${currentDir}/workdata/${dirName}/aln/${dirName}-filterted-variance.vcf.gz ${currentDir}/workdata/${dirName}/aln/${dirName}-variance.vcf.gz &&
    # bcftools stats -F $refFasta ${currentDir}/workdata/${dirName}/aln/${dirName}-filterted-variance.vcf.gz > ${currentDir}/workdata/${dirName}/aln/${dirName}-filtered-variance.stats &&
    # bcftools stats -F $refFasta ${currentDir}/workdata/${dirName}/aln/${dirName}-variance.vcf.gz > ${currentDir}/workdata/${dirName}/aln/${dirName}-nofilter-variance.stats &&
    # plot-vcfstats -P -r -p ${currentDir}/workdata/${dirName}/aln/plots-filter/  ${currentDir}/workdata/${dirName}/aln/${dirName}-filtered-variance.stats &&
    # plot-vcfstats -P -r -p ${currentDir}/workdata/${dirName}/aln/plots-nofilter/ ${currentDir}/workdata/${dirName}/aln/${dirName}-nofilter-variance.stats

    if [ $? != 0 ]; then
        echo "variance call went wrong: ${dirName}"
        exit 1
    fi
done
